/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class analyzer_SSDeep */

#ifndef _Included_analyzer_SSDeep
#define _Included_analyzer_SSDeep
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     analyzer_SSDeep
* Method:    fuzzyCompareNative
* Signature: (Ljava/lang/String;Ljava/lang/String;)I
*/
JNIEXPORT jint JNICALL Java_analyzer_SSDeep_fuzzyCompare
(JNIEnv *, jclass, jstring, jstring);

/*
* Class:     analyzer_SSDeep
* Method:    hashString
* Signature: (Ljava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_analyzer_SSDeep_hashString
(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
